## In this notebook, i am going to learn and practice fundametals concepts of tensors using tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
# create tensors with tf.contant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of tensor
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of our vector
vector.ndim

1

In [10]:
matrix=tf.constant([[1,2],[3,4]])
matrix.ndim

2

In [13]:
# Create another matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16)

In [14]:
another_matrix.ndim

2

Tensor - n dimensional array of numbers

## Creating tensors with `tf.Variable`

In [15]:
# Create the same tensors with tf.variable. These will be same except we can change in the case of variable
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
#unchangeable_tensor[0].assign(7)
unchangeable_tensor[0]=7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Creating Random tensors

In [22]:
# Create tensors of arbitrary size which contain random numbers
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [25]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

##Shuffled

In [8]:
not_shuffled =tf.constant([[10,7],
                          [2,4],
                          [2,5]])
#shuffle non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 2,  4],
       [10,  7]], dtype=int32)>

In [9]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [10]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
tf.ones(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

##Turn numpy array to tensors

In [14]:
import numpy as np

In [17]:
numpy_A=np.arange(1,25,dtype=np.int32)

In [23]:
numpy_A
A=tf.constant(numpy_A, shape=(2,3,4))
B=tf.constant(numpy_A)

## Getting information from tensors


1.   Shape
2.   Rank
1.   Axis or Dim
2.   Size





In [25]:
Tensor=tf.zeros(shape=[2,3,4,5])

In [26]:
Tensor.shape

TensorShape([2, 3, 4, 5])

In [27]:
Tensor.ndim

4

In [28]:
Tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
tf.size(Tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [31]:
# Get various attributes of our tensor
print("Datatype of every element:",Tensor.dtype)
print("Numbers of dimension:",Tensor.ndim)
print("Shape of tensor:",Tensor.shape)
print("Elements along 0 axis:",Tensor.shape[0])
print("Elements along last axis:",Tensor.shape[-1])


Datatype of every element: <dtype: 'float32'>
Numbers of dimension: 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5


## Manipulating tensors (tensor operations)
**Basic Operations**
`+`,`-`,`*`,`/`

In [32]:
tensor_op = tf.constant([[10,7],[2,5]])
tensor_op + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 15]], dtype=int32)>

In [34]:
# Original tensor is unchanged
tensor_op

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [35]:
tensor_op - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -5]], dtype=int32)>

In [36]:
tensor_op * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  50]], dtype=int32)>

In [41]:
## We can use tensorflow built in function
tf.multiply(tensor_op,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  50]], dtype=int32)>

In [42]:
tensor_op

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

**Matrix Multiplication**

In [44]:
tf.matmul(tensor_op,tensor_op)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114, 105],
       [ 30,  39]], dtype=int32)>

In [45]:
tensor_op*tensor_op

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  4,  25]], dtype=int32)>

In [46]:
# Matrix multiplication with python operator @
tensor_op@tensor_op

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114, 105],
       [ 30,  39]], dtype=int32)>

In [50]:
# CReate a tensor of 3,2
X=tf.constant([[1,2],[3,4],[5,6]])
# Create a tensor of 3,2
Y=tf.constant([[5,6],[7,8],[9,10]])
X@tf.transpose(Y)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 17,  23,  29],
       [ 39,  53,  67],
       [ 61,  83, 105]], dtype=int32)>

In [51]:
X@tf.reshape(Y, shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 24, 27],
       [47, 54, 61],
       [73, 84, 95]], dtype=int32)>

**The dot product**
Dot product can be done by using two operations

1.   Matmul
2.   tensordot


In [52]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 5,  6],
        [ 7,  8],
        [ 9, 10]], dtype=int32)>)

In [56]:
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 17,  23,  29],
       [ 39,  53,  67],
       [ 61,  83, 105]], dtype=int32)>

## Changing the datatype of tensor

In [57]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [58]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [59]:
B=tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

## Aggregation

Aggregating tensor is condensing them from multiple values down to asmaller amount

In [60]:
D= tf.constant([-7,-10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [62]:
# Create a random tensor with values between 0 and 100  of size =50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69, 92, 68, 55, 44, 22, 13, 91, 87, 32, 78, 58, 16, 66, 91, 96, 37,
       32, 85,  5, 97,  1, 54,  7, 51, 15, 32, 90, 47, 49, 96, 84, 35, 65,
       68, 70, 97, 99, 74, 86, 84, 16, 38, 88, 26, 44, 31, 40, 72, 14])>

In [63]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [64]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [65]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [66]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2807>

In [71]:
import tensorflow_probability as tfp

In [74]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=865>

In [77]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.41701>

In [78]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=865.3604>

## Find positional minimum or maximum

In [80]:
# Create a new tensor for finding positional minimum or maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [81]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [82]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [83]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [84]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [86]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [87]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [88]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One hot encoding tensor

In [89]:
some_list=[0,1,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# Specify custim values for one hot encoding
tf.one_hot(some_list, depth=4, on_value=True, off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

## Mathematical Opewration

In [91]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [94]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [97]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [101]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [102]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [104]:
numpy_J=tf.constant(np.array([1.,7.,10.]))
numpy_T= tf.constant([1.,7.,10.])
numpy_J.dtype, numpy_T.dtype

(tf.float64, tf.float32)

## finding access to GPU

In [105]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [106]:
tf.config.list_physical_devices("GPU")

[]